#!/bin/bash
# Test script to verify document isolation fix

echo "=== Document Isolation Fix - Test Guide ==="
echo ""
echo "This script provides a testing guide for verifying document isolation."
echo ""

echo "📋 PREREQUISITES:"
echo "  1. Backend server running (make run-dev or docker-compose up)"
echo "  2. Frontend running (cd frontend && npm start)"
echo "  3. User account created and logged in"
echo ""

echo "✅ TEST STEPS:"
echo ""
echo "Test 1: Verify conversation requirement"
echo "  1. Open the chat application"
echo "  2. Before creating any conversation, check the upload button"
echo "  ✓ Should show 'Select Conversation' and be disabled"
echo ""

echo "Test 2: Upload document to Conversation A"
echo "  1. Create a new conversation (Conversation A)"
echo "  2. Upload a document (e.g., 'doc_a.pdf')"
echo "  3. Click 'View Documents'"
echo "  ✓ Should see 'doc_a.pdf' listed"
echo ""

echo "Test 3: Upload document to Conversation B"
echo "  1. Create another conversation (Conversation B)"
echo "  2. Upload a different document (e.g., 'doc_b.pdf')"
echo "  3. Click 'View Documents'"
echo "  ✓ Should see only 'doc_b.pdf' (NOT doc_a.pdf)"
echo ""

echo "Test 4: Verify document isolation"
echo "  1. Switch back to Conversation A"
echo "  2. Click 'View Documents'"
echo "  ✓ Should see only 'doc_a.pdf' (NOT doc_b.pdf)"
echo ""

echo "Test 5: Verify RAG works with correct documents"
echo "  1. In Conversation A, ask a question about content in doc_a.pdf"
echo "  ✓ Should answer using doc_a.pdf content"
echo "  ✓ Source should reference doc_a.pdf"
echo ""
echo "  2. In Conversation B, ask a question about content in doc_b.pdf"
echo "  ✓ Should answer using doc_b.pdf content"
echo "  ✓ Source should reference doc_b.pdf"
echo ""

echo "Test 6: Cross-conversation isolation"
echo "  1. In Conversation A, ask about content ONLY in doc_b.pdf"
echo "  ✓ Should NOT find the information (doc_b is not in this conversation)"
echo "  ✓ Should respond with general knowledge or state info not found"
echo ""

echo "🔍 BACKEND VERIFICATION:"
echo ""
echo "You can verify the SQL queries in the logs:"
echo "  - Check that conversation_id filter is applied in document queries"
echo "  - Check that vector search includes conversation_id constraint"
echo ""

echo "Expected log patterns:"
echo "  'Loaded X document(s) for user Y, conversation Z'"
echo "  'Query mode: rag, Sources: N' (where N is only from current conversation)"
echo ""

echo "🗄️  DATABASE VERIFICATION:"
echo ""
echo "Run these SQL queries to verify data integrity:"
echo ""
echo "-- Check documents are linked to conversations"
echo "SELECT id, filename, conversation_id FROM documents WHERE user_id = YOUR_USER_ID;"
echo ""
echo "-- Verify no orphaned documents (all should have conversation_id)"
echo "SELECT COUNT(*) FROM documents WHERE conversation_id IS NULL;"
echo ""

echo "🎉 SUCCESS CRITERIA:"
echo "  ✅ Documents are only visible in the conversation they were uploaded to"
echo "  ✅ RAG answers only use documents from the current conversation"
echo "  ✅ No cross-contamination between conversations"
echo "  ✅ Upload button requires active conversation"
echo "  ✅ Document list updates when switching conversations"
echo ""

echo "📝 NOTES:"
echo "  - If you had existing documents before this fix, they may have"
echo "    conversation_id = NULL and won't be visible"
echo "  - Each conversation maintains its own isolated document context"
echo "  - This ensures privacy and context clarity"
echo ""

